/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Devices
 #	author : miyako
 #	2015/04/28
 #
 # --------------------------------------------------------------------------------*/



// --- Devices
void DEVICES_LIST(sLONG_PTR *pResult, PackagePtr pParams);

#if VERSIONMAC
#import <DiscRecording/DiscRecording.h>
#else
#include <winioctl.h>
#endif